<?xml version="1.0"?>
<package format="2">
  <name>unk_nav_sim</name>
  <version>0.1.0</version>
  <description>Gazebo simulation environment for unk_nav (Scout v2 + Velodyne HDL-32E)</description>
  <maintainer email="dev@example.com">dev</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>

  <exec_depend>gazebo_ros</exec_depend>
  <exec_depend>scout_gazebo_sim</exec_depend>
  <exec_depend>scout_description</exec_depend>
  <exec_depend>velodyne_description</exec_depend>
  <exec_depend>velodyne_gazebo_plugins</exec_depend>
  <exec_depend>rviz</exec_depend>
</package>
